### PR TITLE
Support only 32bit/64bit Prefixes

### PR DESCRIPTION
**Pull request by Alexander88207**
Yeah some systems like OpenBSD or FreeBSD have only 64bit or only 32bit.

### CODE REVIEW

**Comment by telans** [comment]
I think I made a mistake with this @Alexander88207. system32 should be using wine64, and syswow64 using wine

If you swap those around it should be fine

**Comment by Alexander88207** [comment]
No its right

**Comment by telans** [comment]
As far as I understand it however, system32 is for 64bit and syswow64 for 32bit

**Comment by Alexander88207** [comment]
Then i should drop this pull request. Because the syswow64 folder dont exists in an 32bit only prefix.

**Comment by telans** [comment]
Maybe Wine does it differently, but I know that syswow64 is 32-bit on Windows

**Pull request closed without merging**
