### PR TITLE
Replace Win10 DLLs with Win7 DLLs

### PR DESCRIPTION
**Pull request by FrogTheFrog**
I'm suggesting to replace DLLs, just in case Win10 might be incompatible in some cases.

If you think Win10 DLLs won't cause any problems, then just close this PR :+1:

### CODE REVIEW

**Comment by z0z0z** [comment]
Apparently the guy already tested then win10 dlls with Spyro and they worked. There's a chance these might not work.

As far as I know, that's the only game that even needs these.

It'd be nice if we could test these too with that game, I don't have it.

**Comment by FrogTheFrog** [comment]
I have already tested them, @Waistless could you test Win7 dlls too?

**Comment by Waistless** [comment]
Tested from scratch, works fine for me as well.

**Comment by liberodark** [comment]
is not very good idea better to use windows 10 env for later, windows 7 is now dead

**Comment by z0z0z** [comment]
@liberodark All the original DLLs were Win7. The Windows 10 dlls do not (or did not) work.

**Comment by liberodark** [comment]
ok possibly not supported by wine 4.11.

**Comment by z0z0z** [comment]
All DLLs are from fresh Win7 now. See: https://github.com/z0z0z/mf-install/pull/30

**Pull request closed without merging**
